name: CI Pipeline

on:
  push:
    branches: [main, dev, '*']
  pull_request:
    branches: [main, dev]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install   # root package.json

      - name: Lint frontend
        run: npm run lint

      - name: Format frontend check
        run: npm run format -- --check

      - name: Build frontend
        run: npm run build

  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install backend tools
        run: |
          python3 -m pip install --upgrade pip
          pip install black isort flake8 pre-commit
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi

      - name: Run backend linters
        run: |
          python3 -m black --check backend ml
          python3 -m isort --check-only backend ml
          python3 -m flake8 backend ml

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
