name: Lint & Test

on:
  push:
    branches: [main, dev, '*']
  pull_request:
    branches: [main, dev]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Lint frontend
        run: |
          cd frontend
          npm run lint

      - name: Format frontend check
        run: |
          cd frontend
          npm run format -- --check

  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install backend dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install black isort flake8 pre-commit

      - name: Run backend linters
        run: |
          black --check backend
          isort --check-only backend
          flake8 backend

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
