name: Lint & Test

on:
  push:
    branches: [main, dev, '*']
  pull_request:
    branches: [main, dev]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install frontend dependencies
        run: npm install   # run from root

      - name: Lint frontend
        run: npm run lint

      - name: Format frontend check
        run: npm run format -- --check

  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install tools
        run: |
          python3 -m pip install --upgrade pip
          pip install black isort flake8 pre-commit

      - name: Run backend linters
        run: |
          python3 -m black --check backend ml
          python3 -m isort --check-only backend ml
          python3 -m flake8 backend ml

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
